"""Bake the CC0 TV's geometry and vertex colors for immediate rendering.
Run with python3 scripts/build-tv-preview.py (requires Pillow).
"""
import base64
import hashlib
import json
import struct
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
source = root / 'public/models/television-01'
model = json.loads((source / 'television-01.gltf').read_text())
binary = (source / model['buffers'][0]['uri']).read_bytes()
primitive = model['meshes'][0]['primitives'][0]

def attribute(accessor_id):
    accessor = model['accessors'][accessor_id]
    view = model['bufferViews'][accessor['bufferView']]
    start = view.get('byteOffset', 0) + accessor.get('byteOffset', 0)
    return binary[start:start + view['byteLength']]

position = attribute(primitive['attributes']['POSITION'])
normal = attribute(primitive['attributes']['NORMAL'])
uv = list(struct.iter_unpack('<ff', attribute(primitive['attributes']['TEXCOORD_0'])))
indices = attribute(primitive['indices'])
diffuse = source / 'textures/Television_01_diff_1k.jpg'
image = Image.open(diffuse).convert('RGB')
colors = bytearray()
for u, v in uv:
    rgb = image.getpixel((round((u % 1) * (image.width - 1)), round((v % 1) * (image.height - 1))))
    for c in rgb:
        s = c / 255
        linear = s / 12.92 if s <= 0.04045 else ((s + 0.055) / 1.055) ** 2.4
        colors.append(round(linear * 255))
# Float32 positions/normals, then Uint16 indices, then linear RGB bytes.
data = base64.b64encode(position + normal + indices + colors).decode()
out = root / 'src/three/assets/televisionPreviewData.ts'
out.write_text('// Generated by scripts/build-tv-preview.py from Poly Haven Television_01 (CC0).\n'
               f'export const vertexCount = {len(position) // 12};\n'
               f'export const indexCount = {len(indices) // 2};\n'
               f'export const diffuseDigest = "{hashlib.sha256(diffuse.read_bytes()).hexdigest()}";\n'
               f'export const previewData = "{data}";\n')
